filas/urls.py
from django.contrib import admin
from django.urls import path
from core import views
from core.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.vac_day_index),
    #Postos
    path('posindex/', pos_index, name= "lista_postos"),
    path('poscreate/', pos_create, name= "create_postos"),
    path('posupdate/<int:id_posto>', pos_update, name= "update_postos"),
    path('poshow/<int:id_posto>', pos_show, name= "show_postos"),
    #Postos Específicos
    path('posvacindex/<int:id_posto>', pos_vac_index, name= "lista_postos_vacinas"),
    path('posvacreate/<int:id_posto>', pos_vac_create, name= "create_postos_vacinas"),
    path('delete_postos/<int:id_posto>', delete_postos, name= "delete_postos"),
    #Vacinas
    path('vacindex/', vac_index, name= "lista_vacinas"),
    path('vacreate/', vac_create, name= "create_vacinas"),
    path('vacshow/<int:id_vacina>', vac_show, name= "show_vacinas"),
    path('vacupdate/<int:id_vacina>', vac_update, name= "update_vacinas"),
    path('delete_vacinas/<int:id_vacina>', delete_vacinas, name= "delete_vacinas"),
]

core/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models


# Create your models here.

class dias(models.Model):
    DIAS_CHOICES= [
        [1, "Domingo"],
        [2, "Segunda-feira"],
        [3, "Terça-feira"],
        [4, "Quarta-feira"],
        [5, "Quinta-feira"],
        [6, "Sexta-feira"],
        [7, "Sábado"]
    ]
    dis_dia = models.CharField(max_length = 20 , choices= DIAS_CHOICES)
    def __str__(self):
        return (self.dis_dia)
    class Meta:
        verbose_name_plural = "Dias"

class vacinas(models.Model):
    DISPONIBILIDADE_CHOICES=[
        [1, "Disponível"],
        [0, "Indisponível"]
    ]

    vac_tipo_vacina = models.CharField(max_length = 120)
    vac_lote = models.CharField(max_length = 45)
    vac_fabricante = models.CharField(max_length = 45)
    vac_descricao = models.TextField(max_length = 300)
    vac_quantidade = models.IntegerField()
    vac_disponibilidade = models.BooleanField(choices=DISPONIBILIDADE_CHOICES)
    vac_contraindicacao = models.TextField(max_length = 300)
    vac_reacoes = models.TextField(max_length = 300)
    vac_data_fabricacao = models.DateField()
    vac_data_validade = models.DateField()
    vac_data_recebimento = models.DateField()
    vac_posto = models.ForeignKey("Postos", on_delete=models.CASCADE, related_name='Vacinas')
    vac_dias = models.ManyToManyField("Dias", related_name = "Vacinas")
    def __str__(self):
        return (self.vac_tipo_vacina)
    class Meta:
        verbose_name_plural = "Vacinas"

class postos(models.Model):
    pos_nome = models.CharField(max_length = 120)
    pos_cep = models.CharField(max_length = 45)
    pos_rua = models.CharField(max_length = 45)
    pos_bairro = models.CharField(max_length = 45)
    pos_numero = models.IntegerField()
    pos_logradouro = models.CharField(max_length = 45)
    pos_telefone = models.CharField(max_length = 45)
    def __str__(self):
        return (self.pos_nome)
    class Meta:
        verbose_name_plural = "Postos"
# Create your models here.

core/views.py
from django.shortcuts import render
from .models import *
from django.shortcuts import render, redirect
from core.form import *
from django.utils import timezone
from datetime import date
#Postos
def index(request):
    return render(request, 'admin-dashboard.html')

def pos_index(request):
    posto = postos.objects.all()
    pacote = {"postoChave": posto}
    return render(request, "pos-index.html", pacote)

def pos_create(request):
    form = postosForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("lista_postos")
    
    pacote = {"form_postos": form}
    return render(request, "pos-create.html", pacote)

def  pos_show(request, id_posto):
    posto = postos.objects.get(pk = id_posto)
    pacote = {"postoChave": posto}
    return render(request, "pos-show.html",pacote)

def  pos_vac_index(request, id_posto):
    posto = postos.objects.get(pk = id_posto)
    vacina = vacinas.objects.filter(vac_posto = id_posto)
    pacote = {"postoChave": posto, "vacinasChave": vacina}
    return render(request, "pos-vac-index.html",pacote)

def pos_vac_create(request,id_posto):
    form = vacinasForm(request.POST or None)
    form.fields["vac_posto"].initial = id_posto
    if form.is_valid():
        form.save()       
        return redirect("lista_vacinas")
    pacote = {"form_vacinas": form}
    return render(request, "pos-vac-create.html", pacote)

def pos_update(request, id_posto):
    posto = postos.objects.get(pk = id_posto)
    form = postosForm(request.POST or None, instance = posto)
    if form.is_valid():
        form.save()
        return redirect("lista_postos")
    
    pacote = {"form_postos": form , "postoChave": posto}
    return render(request, "pos-update.html", pacote)

def delete_postos(request, id_posto):
    posto = postos.objects.get(pk = id_posto)
    posto.delete()
    return redirect("lista_postos")

#Vacinas
def vac_index(request):
    vacina = vacinas.objects.all()
    pacote = {"vacinaChave": vacina}
    return render(request, "vac-index.html", pacote)

def vac_day_index(request):
    hoje = timezone.now()
    data = hoje.isoweekday()
    x = date.today()
    vacina = vacinas.objects.filter(vac_disponibilidade = 1, vac_dias = data)
    pacote = {"vacinaChave": vacina, "dia":x}
    return render(request, "vac-day-index.html", pacote)

def vac_create(request):
    form = vacinasForm(request.POST or None)
    if form.is_valid():
        form.save()       
        return redirect("lista_vacinas")
    pacote = {"form_vacinas": form}
    return render(request, "vac-create.html", pacote)

def  vac_show(request, id_vacina):
    vacina = vacinas.objects.get(pk = id_vacina)
    dias = vacina.vac_dias.all()
    pacote = {"vacinaChave": vacina, "dias":dias}
    return render(request, "vac-show.html",pacote)

def vac_update(request, id_vacina):
    vacina = vacinas.objects.get(pk = id_vacina)
    form = vacinasForm(request.POST or None, instance = vacina)
    if form.is_valid():
        form.save()
        return redirect("lista_vacinas")
    
    pacote = {"form_vacinas": form , "vacinaChave": vacina}
    return render(request, "vac-update.html", pacote)

def delete_vacinas(request, id_vacina):
    vacina = vacinas.objects.get(pk = id_vacina)
    vacina.delete()
    return redirect("lista_vacinas")

core/templates/admin-dashboard.html
{%extends 'layouts/pages-blank.html'%}

{%block title %}Admin Dashboard{%endblock title%}


{%block main-content%}
<div class="container">
  <div class="row">
      <div class="col-lg-3">
          <!-- Default Card -->
          <div class="card admin-card">
            <div class="card-body">
              <h5 class="card-title">Gerenciar Postos</h5>
            </div>
          </div><!-- End Default Card -->
      </div>
                
      <div class="col-lg-3">
            <!-- Default Card -->
            <div class="card admin-card">
                <div class="card-body">
                  <h5 class="card-title">Gerenciar Vacinas</h5>
                </div>
            </div><!-- End Default Card -->
      </div>
  </div>
</div>
{%endblock main-content%}

core/templates/pos-create.html
{%extends 'layouts/pages-blank.html'%}

{%block title %}Postos{%endblock title%}

{%block page-name%}Cadastro de Postos{%endblock page-name%}

{%block directory%}
<li class="breadcrumb-item"><a href="index.html">Home</a></li>
<li class="breadcrumb-item">Postos</li>
<li class="breadcrumb-item"><a href="{%url 'lista_postos'%}">Listar Postos</a></li>
<li class="breadcrumb-item active">Cadastrar Posto</li>
{%endblock directory%}


{%block main-content%}
<div class="card">
    <div class="card-body">
      
      <!-- Vertical Form -->
      <form class="row g-3" method="POST" id="create_form">
        {% csrf_token %}
        <h5 class="card-title">Informações Gerais</h5>
        <div class="col-12">
          <label for="inputNanme4" class="form-label">Nome</label>
          {{form_postos.pos_nome}}
        </div>
        <div class="col-3">
            <label for="inputNanme4" class="form-label">Horário de funcionamento</label>
            <input type="text" class="form-control" id="inputNanme4">
        </div>
        <h5 class="card-title">Localização</h5>
        <div class="col-12">
            <label for="id_pos_cep" class="form-label">Cep</label>
            {{form_postos.pos_cep}}
        </div>
        <div class="col-4">
            <label for="id_pos_bairo" class="form-label">Bairro</label>
            {{form_postos.pos_bairro}}
        </div>
        <div class="col-4">
            <label for="id_pos_rua" class="form-label">Rua</label>
            {{form_postos.pos_rua}}
        </div>
        <div class="col-2">
          <label for="id_pos_numero" class="col-sm-6 form-label">Número</label>
          {{form_postos.pos_numero}}
        </div>
        <div class="col-12">
            <label for="id_pos_logradouro" class="form-label">Logradouro</label>
            {{form_postos.pos_logradouro}}
        </div>
        <h5 class="card-title">Contato</h5>
        <div class="col-4">
            <label for="id_pos_telefone" class="form-label">Telefone</label>
            {{form_postos.pos_telefone}}
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
      </form><!-- Vertical Form -->

    </div>
  </div>
{%endblock main-content%}

core/templates/pos-index.html
{%extends 'layouts/pages-blank.html'%}

{%block title %}Postos{%endblock title%}

{%block page-name%}Lista de Postos{%endblock page-name%}

{%block directory%}
<li class="breadcrumb-item"><a href="index.html">Home</a></li>
<li class="breadcrumb-item">Postos</li>
<li class="breadcrumb-item active">Listar Postos</li>
{%endblock directory%}


{%block main-content%}
<a href= "{% url 'create_postos'%}"> 
<button type="button" class="btn btn-primary">
  <i class="bx bxs-edit"></i>
  Cadastrar Posto
</button>
</a>
<!-- Default Table -->
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Posto</th>
      <th scope="col">Cep</th>
      <th scope="col">Bairro</th>
      <th scope="col">Rua</th>     
      <th scope="col">Número</th>     
      <th scope="col">Telefone</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    {%for i in postoChave%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.pos_nome}} </td>
        <td>{{i.pos_cep}} </td>
        <td>{{i.pos_bairro}} </td>
        <td>{{i.pos_rua}} </td>
        <td>{{i.pos_numero}} </td>
        <td>{{i.pos_telefone}} </td>
        <td>
          <a href="{%url 'show_postos' i.id%}" class="text-primary fw-bold">Exibir</a>
          <a href="{%url 'update_postos' i.id%}" class="text-primary fw-bold">Editar</a>
          <a href="{%url 'delete_postos' i.id%}" class="text-primary fw-bold">Excluir</a>
        </td>
    </tr>
    {%endfor%}
  </tbody>
</table>
<!-- End Default Table Example -->
{%endblock main-content%}

core/templates/pos-show.html
{%extends 'layouts/pages-blank.html'%}

{%block title %}{{postoChave.pos_nome}}{%endblock title%}

{%block page-name%}{{postoChave.pos_nome}}{%endblock page-name%}

{%block directory%}
<li class="breadcrumb-item"><a href="index.html">Home</a></li>
<li class="breadcrumb-item">Postos</li>
<li class="breadcrumb-item"><a href="{%url 'lista_postos'%}">Listar Postos</a></li>
<li class="breadcrumb-item active">Exibir {{postoChave.pos_nome}}</li>
{%endblock directory%}


{%block main-content%}
<div class="row">
    <div class="col-xl-4">

      <div class="card">
        <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
          <h2>{{postoChave.pos_nome}}</h2>
        </div>
      </div>

    </div>

    <div class="col-xl-8">

      <div class="card">
        <div class="card-body pt-3">
          <div class="tab-content pt-2">

            <div class="tab-pane fade show active profile-overview" id="profile-overview">

              <div class="row">
                <div class="col-lg-3 col-md-4 label ">Nome</div>
                <div class="col-lg-9 col-md-8">{{postoChave.pos_nome}}</div>
              </div>

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Cep</div>
                <div class="col-lg-9 col-md-8">{{postoChave.pos_cep}}</div>
              </div>

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Bairro</div>
                <div class="col-lg-9 col-md-8">{{postoChave.pos_bairro}}</div>
              </div>

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Rua</div>
                <div class="col-lg-9 col-md-8">{{postoChave.pos_rua}}</div>
              </div>

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Número</div>
                <div class="col-lg-9 col-md-8">{{postoChave.pos_numero}}</div>
              </div>

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Logradouro</div>
                <div class="col-lg-9 col-md-8">{{postoChave.pos_logradouro}}</div>
              </div>

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Telefone</div>
                <div class="col-lg-9 col-md-8">{{postoChave.pos_telefone}}</div>
              </div>
              </div>
            </div>
          </div><!-- End Bordered Tabs -->
        </div>
        <div class="offset-5">
          <a href= "{% url 'lista_postos_vacinas' postoChave.id%}"> 
            <button type="button" class="btn btn-primary">
              Listar Vacinas
            </button>
          </a>
          <a href= "{%url 'update_postos' postoChave.id%}"> 
            <button type="button" class="btn btn-primary">
              Editar Posto
            </button>
          </a>
          <a href= "{%url 'delete_postos' postoChave.id%}"> 
            <button type="button" class="btn btn-danger">
              Deletar Posto
            </button>
          </a>
        </div>
      </div>
    </div>
  </div>
{%endblock main-content%}

core/templates/pos-update.html
{%extends 'layouts/pages-blank.html'%}

{%block title %}{{postoChave.pos_nome}}{%endblock title%}

{%block page-name%}Editar posto: {{postoChave.pos_nome}}{%endblock page-name%}

{%block directory%}
<li class="breadcrumb-item"><a href="index.html">Home</a></li>
<li class="breadcrumb-item">Postos</li>
<li class="breadcrumb-item"><a href="{%url 'lista_postos'%}">Listar Postos</a></li>
<li class="breadcrumb-item active">Editar {{postoChave.pos_nome}}</li>
{%endblock directory%}


{%block main-content%}
<div class="card">
    <div class="card-body">
      
      <!-- Vertical Form -->
      <form class="row g-3" method="POST" id="create_form">
        {% csrf_token %}
        <h5 class="card-title">Informações Gerais</h5>
        <div class="col-12">
          <label for="inputNanme4" class="form-label">Nome</label>
          {{form_postos.pos_nome}}
        </div>
        <div class="col-3">
            <label for="inputNanme4" class="form-label">Horário de funcionamento</label>
            <input type="text" class="form-control" id="inputNanme4">
        </div>
        <h5 class="card-title">Localização</h5>
        <div class="col-12">
            <label for="id_pos_cep" class="form-label">Cep</label>
            {{form_postos.pos_cep}}
        </div>
        <div class="col-4">
            <label for="id_pos_bairo" class="form-label">Bairro</label>
            {{form_postos.pos_bairro}}
        </div>
        <div class="col-4">
            <label for="id_pos_rua" class="form-label">Rua</label>
            {{form_postos.pos_rua}}
        </div>
        <div class="col-2">
          <label for="id_pos_numero" class="col-sm-6 form-label">Número</label>
          {{form_postos.pos_numero}}
        </div>
        <div class="col-12">
            <label for="id_pos_logradouro" class="form-label">Logradouro</label>
            {{form_postos.pos_logradouro}}
        </div>
        <h5 class="card-title">Contato</h5>
        <div class="col-4">
            <label for="id_pos_telefone" class="form-label">Telefone</label>
            {{form_postos.pos_telefone}}
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Create</button>
        </div>
      </form><!-- Vertical Form -->

    </div>
  </div>
{%endblock main-content%}

core/templates/pos-vac-create.html
{%extends 'layouts/pages-blank.html'%}

{%block title %}Cadastro de Vacinas{%endblock title%}

{%block page-name%}Cadastrar Nova Vacina{%endblock page-name%}

{%block directory%}
<li class="breadcrumb-item"><a href="index.html">Home</a></li>
<li class="breadcrumb-item">Vacinas</li>
<li class="breadcrumb-item"><a href="{%url 'lista_vacinas'%}">Listar Vacinas</a></li>
<li class="breadcrumb-item active">Cadastrar Vacina</li>
{%endblock directory%}

{%block main-content%}
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Cadastrar Vacina</h5>

      <!-- Vertical Form -->
      <form class="row g-3" id="create_form" method="POST">
        {% csrf_token %}
        <div class="col-4">
          <label for="id_vac_tipo_vacina" class="form-label">Tipo Vacina</label>
          {{form_vacinas.vac_tipo_vacina}}
        </div>
        <div class="col-4">
          <label for="id_vac_posto" class="form-label">Posto</label>
          {{form_vacinas.vac_posto}}
        </div>
        <div class="col-4">
          <label for="id_vac_disponibilidade" class="form-label">Disponibilidade</label>
          {{form_vacinas.vac_disponibilidade}}
        </div>
        <div class="col-12">
          <label for="id_vac_descricao" class="col-sm-2 col-form-label">Descrição</label>
          {{form_vacinas.vac_descricao}}
        </div>
        <div class="col-3">
          <label for="id_vac_quantidade" class="form-label">Quantidade</label>
          {{form_vacinas.vac_quantidade}}
        </div>
        <div class="col-3">
          <label for="id_vac_data_fabricacao" class="form-label">Data de Fabricação</label>
          <input type="date" class="form-control" id="id_vac_data_fabricacao" name="vac_data_fabricacao">
        </div>
        <div class="col-3">
          <label for="id_vac_data_validade" class="form-label">Data de Validade</label>
          <input type="date" class="form-control" id="id_vac_data_validade" name="vac_data_validade">
        </div>
        <div class="col-3">
          <label for="id_vac_data_recebimento" class="form-label">Data de Recebimento</label>
          <input type="date" class="form-control" id="id_vac_data_recebimento" name="vac_data_recebimento">
        </div>
        <div class="col-12">
          <label for="id_vac_contraindicacao" class="col-sm-2 col-form-label">Contraindicações</label>
          {{form_vacinas.vac_contraindicacao}}
        </div>
        <div class="col-12">
          <label for="id_vac_reacoes" class="col-sm-2 col-form-label">Reações</label>
          {{form_vacinas.vac_reacoes}}
        </div>
        <div class="col-6">
          <label for="id_vac_lote" class="form-label">Lote</label>
          {{form_vacinas.vac_lote}}
        </div>  
        <div class="col-6">
          <label for="id_vac_fabricante" class="form-label">Fabricante</label>
          {{form_vacinas.vac_fabricante}}
        </div>
               

        <div class="text-center">
          <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
      </form><!-- Vertical Form -->
    </div>
  </div>
{%endblock main-content%}

core/templates/vac-create.html
{%extends 'layouts/pages-blank.html'%}

{%block title %}Cadastro de Vacinas{%endblock title%}

{%block page-name%}Cadastrar Nova Vacina{%endblock page-name%}

{%block directory%}
<li class="breadcrumb-item"><a href="index.html">Home</a></li>
<li class="breadcrumb-item">Vacinas</li>
<li class="breadcrumb-item"><a href="{%url 'lista_vacinas'%}">Listar Vacinas</a></li>
<li class="breadcrumb-item active">Cadastrar Vacina</li>
{%endblock directory%}

{%block main-content%}
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Cadastrar Vacina</h5>

      <!-- Vertical Form -->
      <form class="row g-3" id="create_form" method="POST">
        {% csrf_token %}
        <div class="col-4">
          <label for="id_vac_tipo_vacina" class="form-label">Tipo Vacina</label>
          {{form_vacinas.vac_tipo_vacina}}
        </div>
        <div class="col-4">
          <label for="id_vac_posto" class="form-label">Posto</label>
          {{form_vacinas.vac_posto}}
        </div>
        <div class="col-4">
          <label for="id_vac_disponibilidade" class="form-label">Disponibilidade</label>
          {{form_vacinas.vac_disponibilidade}}
        </div>
        <div class="col-12">
          <label for="id_vac_descricao" class="col-sm-2 col-form-label">Descrição</label>
          {{form_vacinas.vac_descricao}}
        </div>
        <div class="col-3">
          <label for="id_vac_quantidade" class="form-label">Quantidade</label>
          {{form_vacinas.vac_quantidade}}
        </div>
        <div class="col-3">
          <label for="id_vac_data_fabricacao" class="form-label">Data de Fabricação</label>
          <input type="date" class="form-control" id="id_vac_data_fabricacao" name="vac_data_fabricacao">
        </div>
        <div class="col-3">
          <label for="id_vac_data_validade" class="form-label">Data de Validade</label>
          <input type="date" class="form-control" id="id_vac_data_validade" name="vac_data_validade">
        </div>
        <div class="col-3">
          <label for="id_vac_data_recebimento" class="form-label">Data de Recebimento</label>
          <input type="date" class="form-control" id="id_vac_data_recebimento" name="vac_data_recebimento">
        </div>
        <div class="col-12">
          <label for="id_vac_contraindicacao" class="col-sm-2 col-form-label">Contraindicações</label>
          {{form_vacinas.vac_contraindicacao}}
        </div>
        <div class="col-12">
          <label for="id_vac_reacoes" class="col-sm-2 col-form-label">Reações</label>
          {{form_vacinas.vac_reacoes}}
        </div>
        <div class="col-6">
          <label for="id_vac_lote" class="form-label">Lote</label>
          {{form_vacinas.vac_lote}}
        </div>  
        <div class="col-6">
          <label for="id_vac_fabricante" class="form-label">Fabricante</label>
          {{form_vacinas.vac_fabricante}}
        </div>
        <div class="col-6">
          <label for="id_vac_dias" class="form-label">Dias:</label>
          <div>
          {%for campo in form_vacinas.vac_dias%}
          {{campo}}
          {%endfor%}
          </div>
        </div>

        <div class="text-center">
          <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
      </form><!-- Vertical Form -->
    </div>
  </div>
{%endblock main-content%}

core/templates/vac-update.html
{%extends 'layouts/pages-blank.html'%}

{%block title %}Editar Vacina{%endblock title%}

{%block page-name%}Atualizar vacina: {{vacinaChave.vac_tipo_vacina}}{%endblock page-name%}

{%block directory%}
<li class="breadcrumb-item"><a href="index.html">Home</a></li>
<li class="breadcrumb-item">Vacinas</li>
<li class="breadcrumb-item"><a href="{%url 'lista_vacinas'%}">Listar Vacinas</a></li>
<li class="breadcrumb-item active">Editar {{vacinaChave.vac_tipo_vacina}}</li>
{%endblock directory%}

{%block main-content%}
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Editar {{vacinaChave.vac_tipo_vacina}}</h5>

      <!-- Vertical Form -->
      <form class="row g-3" id="create_form" method="POST">
        {% csrf_token %}
        <div class="col-4">
          <label for="id_vac_tipo_vacina" class="form-label">Tipo Vacina</label>
          {{form_vacinas.vac_tipo_vacina}}
        </div>
        <div class="col-4">
          <label for="id_vac_posto" class="form-label">Posto</label>
          {{form_vacinas.vac_posto}}
        </div>
        <div class="col-4">
          <label for="id_vac_disponibilidade" class="form-label">Disponibilidade</label>
          {{form_vacinas.vac_disponibilidade}}
        </div>
        <div class="col-12">
          <label for="id_vac_descricao" class="col-sm-2 col-form-label">Descrição</label>
          {{form_vacinas.vac_descricao}}
        </div>
        <div class="col-3">
          <label for="id_vac_quantidade" class="form-label">Quantidade</label>
          {{form_vacinas.vac_quantidade}}
        </div>
        <div class="col-3">
          <label for="id_vac_data_fabricacao" class="form-label">Data de Fabricação</label>
          {{form_vacinas.vac_data_fabricacao}}
        </div>
        <div class="col-3">
          <label for="id_vac_data_validade" class="form-label">Data de Validade</label>
          {{form_vacinas.vac_data_validade}}
        </div>
        <div class="col-3">
          <label for="id_vac_data_recebimento" class="form-label">Data de Recebimento</label>
          {{form_vacinas.vac_data_recebimento}}
        </div>
        <div class="col-12">
          <label for="id_vac_contraindicacao" class="col-sm-2 col-form-label">Contraindicações</label>
          {{form_vacinas.vac_contraindicacao}}
        </div>
        <div class="col-12">
          <label for="id_vac_reacoes" class="col-sm-2 col-form-label">Reações</label>
          {{form_vacinas.vac_reacoes}}
        </div>
        <div class="col-6">
          <label for="id_vac_lote" class="form-label">Lote</label>
          {{form_vacinas.vac_lote}}
        </div>  
        <div class="col-6">
          <label for="id_vac_fabricante" class="form-label">Fabricante</label>
          {{form_vacinas.vac_fabricante}}
        </div> 
        <div class="col-6">
          <label for="id_vac_dias" class="form-label">Dias:</label>
          <div>
          {%for campo in form_vacinas.vac_dias%}
          {{campo}}
          {%endfor%}
          </div>
        </div>       
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
      </form><!-- Vertical Form -->
    </div>
  </div>
{%endblock main-content%}